version: '3'
services:
  seleniumChrome:
    image: shiweiwei97/selenium-grid-extras-chrome:3.8.1-2.0.4-85.0
    build: .
    container_name: selenium-grid-extras-chrome
    restart: unless-stopped
    shm_size: 2g
    ports:
      - "5555:5555"
      - "3100:3000"
    depends_on:
      - seleniumHub
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
  seleniumHub:
    image: shiweiwei97/selenium-grid-extras-hub:2.0.4
    container_name: selenium-grid-extras-hub
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "3000:3000"
