version: '3'
services:
  seleniumChrome:
    image: shiweiwei97/selenium-grid-extras-chrome:3.8.1-2.0.4-85.0
    container_name: selenium-grid-extras-chrome
    restart: unless-stopped
    shm_size: 2g
    ports:
      - "5555:5555"
      - "3100:3000"
    depends_on:
      - seleniumHub
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
#       - ./custom_grid_config.json:/opt/selenium/selenium_grid_extras_config.json
#       - ./custom_node_config.json:/opt/selenium/node_5555.json
  seleniumFirefox:
    image: shiweiwei97/selenium-grid-extras-firefox:3.8.1-2.0.4-80.0
    container_name: selenium-grid-extras-firefox
    restart: unless-stopped
    shm_size: 2g
    ports:
      - "5556:5555"
      - "3200:3000"
    depends_on:
      - seleniumHub
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
#    volumes:
#       - ./custom_grid_config.json:/opt/selenium/selenium_grid_extras_config.json
#       - ./custom_node_config.json:/opt/selenium/node_5555.json
  seleniumHub:
    image: shiweiwei97/selenium-grid-extras-hub:2.0.4
    container_name: selenium-grid-extras-hub
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "3000:3000"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
#     - SE_OPTS=-debug true
#    volumes:
#       - ./custom_grid_config.json:/opt/selenium/selenium_grid_extras_config.json
#       - ./custom_hub_config.json:/opt/selenium/hub_4444.json
#       - ./log4j.properties:/opt/selenium/log4j.properties